monitor-tool/ViewModels/ICMPNodeCreate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MonitoringTool.ViewModels
{
    public class ICMPNodeCreate
    {
        public string Name { get; set; }
        public string Host { get; set; }
    }
}

monitor-tool/ViewModels/UnseenDowntime.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MonitoringTool.ViewModels
{
    public class UnseenDowntime
    {
        public Domain.Core.Node Node { get; set; }

        public Domain.Downtimes.Downtime Downtime { get; set; }
    }
}

monitor-tool/ViewModels/UrlNodeCreate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MonitoringTool.ViewModels
{
    public class UrlNodeCreate
    {
        public string Name { get; set; }
        public string Url { get; set; }
    }
}

monitor-tool/Controllers/DowntimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoRepository;
using MonitoringTool.Domain.Core;
using MonitoringTool.Domain.Downtimes;
using MonitoringTool.ViewModels;

namespace MonitoringTool.Controllers
{
    public class DowntimeController : Controller
    {
        public ActionResult Index(string Id)
        {
            MongoRepository<Node> nodes = new MongoRepository<Node>();
            MongoRepository<Downtime> downtimes = new MongoRepository<Downtime>();
            Node node = nodes.FirstOrDefault(o => o.Id == Id);
            if (node == null)
                return RedirectToAction("Index", "Home");

            return View(downtimes.Where(o => o.NodeId == node.Id).ToList());
        }

        public ActionResult Seen(string id)
        {
            MongoRepository<Downtime> downtimes = new MongoRepository<Downtime>();
            Downtime downtime = downtimes.GetById(id);
            if (downtime != null)
            {
                downtime.Seen = true;
                downtimes.Update(downtime);
            }

            return Json(new { Success = true }, JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetUnseenDowntime()
        {
            MongoRepository<Downtime> downtimes = new MongoRepository<Downtime>();
            MongoRepository<Node> nodes = new MongoRepository<Node>();
            return Json(downtimes.Where(o => !o.Seen).Select(x => new UnseenDowntime()
                {
                    Node = nodes.GetById(x.NodeId),
                    Downtime = x
                }).ToList(), JsonRequestBehavior.AllowGet);
        }
    }
}

monitor-tool/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoRepository;
using MonitoringTool.Domain.Core;

namespace MonitoringTool.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            MongoRepository<Node> nodes = new MongoRepository<Node>();
            return View(nodes.ToList().Cast<Node>().ToList());
        }
    }
}

monitor-tool/Controllers/ICMPNodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoRepository;
using MonitoringTool.Domain.Core;
using MonitoringTool.ViewModels;

namespace MonitoringTool.Controllers
{
    public class ICMPNodeController : Controller
    {
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ICMPNodeCreate icmpNodeCreate)
        {
            if (icmpNodeCreate.Host != null && icmpNodeCreate.Name != null)
            {
                MongoRepository<Node> nodes = new MongoRepository<Node>();
                nodes.Add(new ICMPNode()
                {
                    Name = icmpNodeCreate.Name,
                    Host = icmpNodeCreate.Host
                });

                return RedirectToAction("Index", "Home");
            }

            return View(icmpNodeCreate);
        }
    }
}

monitor-tool/Controllers/NodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoRepository;
using MonitoringTool.Domain.Core;
using MonitoringTool.ViewModels;

namespace MonitoringTool.Controllers
{
    public class NodeController : Controller
    {
        public ActionResult Remove(string Id)
        {
            MongoRepository<Node> nodes = new MongoRepository<Node>();
            nodes.Delete(Id);
            return RedirectToAction("Index", "Home");
        }
    }
}

monitor-tool/Controllers/UrlNodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MongoRepository;
using MonitoringTool.Domain.Core;
using MonitoringTool.ViewModels;

namespace MonitoringTool.Controllers
{
    public class UrlNodeController : Controller
    {
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(UrlNodeCreate urlNodeCreate)
        {
            if (urlNodeCreate.Name != null && urlNodeCreate.Url != null)
            {
                MongoRepository<Node> nodes = new MongoRepository<Node>();
                nodes.Add(new UrlNode()
                {
                    Name = urlNodeCreate.Name,
                    Url = urlNodeCreate.Url
                });

                return RedirectToAction("Index", "Home");
            }

            return View(urlNodeCreate);
        }
    }
}

monitor-tool/Views/Downtime/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Html.SetActive(MenuItems.DASHBOARD);
}
@model IEnumerable<MonitoringTool.Domain.Downtimes.Downtime>
           <script type="text/javascript">
                   setTimeout(function() {
                       window.location = window.location.href;
                   }, 30000);
           </script>
<table class="table">

    <thead>
        <tr><th>From</th><th>Till</th><th></th></tr>
    </thead>
    <tbody>
        @if (Model.Any())
{
    foreach (var downtime in Model)
    {

        <tr class="@((downtime.Stop == null)?"danger":"")">
            <td>@downtime.Start.ToLocalTime().ToShortTimeString() @downtime.Start.ToLocalTime().ToShortDateString()</td>
            <td>@if (downtime.Stop != null)
{
                    <span>@downtime.Stop.Value.ToLocalTime().ToShortTimeString()</span>
                    <span>@downtime.Stop.Value.ToLocalTime().ToShortDateString()</span>
                }
            </td>
            <td>
                @Math.Floor(downtime.Duration.TotalHours).ToString().PadLeft(2, '0'):@downtime.Duration.ToString("mm"):@downtime.Duration.ToString("ss")
            </td>
        </tr>
    }
}
else
{
            <tr><td colspan="2">No rows</td></tr>
        }
    </tbody> 



</table>

monitor-tool/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

monitor-tool/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

monitor-tool/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Html.SetActive(MenuItems.DASHBOARD);
}
@model IEnumerable<MonitoringTool.Domain.Core.Node>
           <script type="text/javascript">
                   setTimeout(function(){
                       window.location = window.location.href;
                   }, 30000);
           </script>
<table class="table">

    <thead>
        <tr><th>Name</th><th>Online</th><th></th></tr>
    </thead>
    <tbody>
        @if (Model.Any())
        {
            foreach (var node in Model)
            {
                
                <tr class="@((!node.Online)?"danger":"")"><td>@Html.ActionLink(node.Name, "Index", "Downtime", new { Id = node.Id }, new { })</td><td>@node.Online</td><td><a href="@Url.Action("Remove", "Node", new { Id = node.Id })" class="glyphicon glyphicon-remove" onclick="return confirm('Sure?');"></a></td></tr>
            }
        }
        else
        {
            <tr><td colspan="4">No rows</td></tr>
        }
    </tbody>



</table>

monitor-tool/Views/ICMPNode/Create.cshtml
@model MonitoringTool.ViewModels.ICMPNodeCreate

@{
    ViewBag.Title = "Create";
    Html.SetActive(MenuItems.CREATE_NODE);
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ICMPNode</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Host, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Host)
                @Html.ValidationMessageFor(model => model.Host)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

monitor-tool/Views/UrlNode/Create.cshtml
@model MonitoringTool.ViewModels.UrlNodeCreate

@{
    ViewBag.Title = "Create";
    Html.SetActive(MenuItems.CREATE_NODE);
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UrlNode</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url)
                @Html.ValidationMessageFor(model => model.Url)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>